import "./globals.css";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import ThemeProvider from "@/theme/themeProvider";
import LayoutPage from "@/components/mainLayout/Layout";
import connectToDB from "@/config/db";
import { SessionProvider } from "next-auth/react";
import SessionWrapper from "@/components/session/SessionWraper";

const vazir = Vazirmatn({ subsets: ["latin"], variable: "--font-vazir" });

export const metadata: Metadata = {
  title: "yoones",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectToDB();
  return (
    <SessionWrapper>
      <html lang="en" dir="ltr">
        <body className={vazir.variable}>
          <ThemeProvider>
            <AntdRegistry>
              <LayoutPage children={children} />
            </AntdRegistry>
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
